dpt_nom = {
    1 : "Ain",
    2 : "Aisne",
    3 : "Allier",
    4 : "Alpes-de-Haute-Provence",
    5 : "Hautes-Alpes",
    6 : "Alpes-Maritimes",
    7 : "Ardèche",
    8 : "Ardennes",
    9 : "Ariège",
    10 : "Aube",
    11 : "Aude",
    12 : "Aveyron",
    13 : "Bouches-du-Rhône",
    14 : "Calvados",
    15 : "Cantal",
    16 : "Charente",
    17 : "Charente-Maritime",
    18 : "Cher",
    19 : "Corrèze",
    '2A' : "Corse-du-Sud",
    '2B' : "Haute-Corse",
    21 : "Côte-d'Or",
    22 : "Côtes-d'Armor",
    23 : "Creuse",
    24 : "Dordogne",
    25 : "Doubs",
    26 : "Drôme",
    27 : "Eure",
    28 : "Eure-et-Loir",
    29 : "Finistère",
    30 : "Gard",
    31 : "Haute-Garonne",
    32 : "Gers",
    33 : "Gironde",
    34 : "Hérault",
    35 : "Ille-et-Vilaine",
    36 : "Indre",
    37 : "Indre-et-Loire",
    38 : "Isère",
    39 : "Jura",
    40 : "Landes",
    41 : "Loir-et-Cher",
    42 : "Loire",
    43 : "Haute-Loire",
    44 : "Loire-Atlantique",
    45 : "Loiret",
    46 : "Lot",
    47 : "Lot-et-Garonne",
    48 : "Lozère",
    49 : "Maine-et-Loire",
    50 : "Manche",
    51 : "Marne",
    52 : "Haute-Marne",
    53 : "Mayenne",
    54 : "Meurthe-et-Moselle",
    55 : "Meuse",
    56 : "Morbihan",
    57 : "Moselle",
    58 : "Nièvre",
    59 : "Nord",
    60 : "Oise",
    61 : "Orne",
    62 : "Pas-de-Calais",
    63 : "Puy-de-Dôme",
    64 : "Pyrénées-Atlantiques",
    65 : "Hautes-Pyrénées",
    66 : "Pyrénées-Orientales",
    67 : "Bas-Rhin",
    68 : "Haut-Rhin",
    '69D' : "Rhône",
    '69M' : "Métropole de Lyon",
    70 : "Haute-Saône",
    71 : "Saône-et-Loire",
    72 : "Sarthe",
    73 : "Savoie",
    74 : "Haute-Savoie",
    75 : "Paris",
    76 : "Seine-Maritime",
    77 : "Seine-et-Marne",
    78 : "Yvelines",
    79 : "Deux-Sèvres",
    80 : "Somme",
    81 : "Tarn",
    82 : "Tarn-et-Garonne",
    83 : "Var",
    84 : "Vaucluse",
    85 : "Vendée",
    86 : "Vienne",
    87 : "Haute-Vienne",
    88 : "Vosges",
    89 : "Yonne",
    90 : "Territoire de Belfort",
    91 : "Essonne",
    92 : "Hauts-de-Seine",
    93 : "Seine-Saint-Denis",
    94 : "Val-de-Marne",
    95 : "Val-d'Oise",
    971 : "Guadeloupe",
    972 : "Martinique",
    973 : "Guyane",
    974 : "La Réunion",
    976 : "Mayotte",
}

dpt_region = {
    1 : "Auvergne-Rhône-Alpes",
    2 : "Hauts-de-France",
    3 : "Auvergne-Rhône-Alpes",
    4 : "Provence-Alpes-Côte d'Azur",
    5 : "Provence-Alpes-Côte d'Azur",
    6 : "Provence-Alpes-Côte d'Azur",
    7 : "Auvergne-Rhône-Alpes",
    8 : "Grand Est",
    9 : "Occitanie",
    10 : "Grand Est",
    11 : "Occitanie",
    12 : "Occitanie",
    13 : "Provence-Alpes-Côte d'Azur",
    14 : "Normandie",
    15 : "Auvergne-Rhône-Alpes",
    16 : "Nouvelle-Aquitaine",
    17 : "Nouvelle-Aquitaine",
    18 : "Centre-Val de Loire",
    19 : "Nouvelle-Aquitaine",
    '2A' : "Corse",
    '2B' : "Corse",
    21 : "Bourgogne-France-Comté",
    22 : "Bretagne",
    23 : "Nouvelle-Aquitaine",
    24 : "Nouvelle-Aquitaine",
    25 : "Bourgogne-France-Comté",
    26 : "Auvergne-Rhône-Alpes",
    27 : "Normandie",
    28 : "Centre-Val de Loire",
    29 : "Bretagne",
    30 : "Occitanie",
    31 : "Occitanie",
    32 : "Occitanie",
    33 : "Nouvelle-Aquitaine",
    34 : "Occitanie",
    35 : "Bretagne",
    36 : "Centre-Val de Loire",
    37 : "Centre-Val de Loire",
    38 : "Auvergne-Rhône-Alpes",
    39 : "Bourgogne-France-Comté",
    40 : "Nouvelle-Aquitaine",
    41 : "Centre-Val de Loire",
    42 : "Auvergne-Rhône-Alpes",
    43 : "Auvergne-Rhône-Alpes",
    44 : "Pays de la loire",
    45 : "Centre-Val de Loire",
    46 : "Occitanie",
    47 : "Nouvelle-Aquitaine",
    48 : "Occitanie",
    49 : "Pays de la loire",
    50 : "Normandie",
    51 : "Grand Est",
    52 : "Grand Est",
    53 : "Pays de la loire",
    54 : "Grand Est",
    55 : "Grand Est",
    56 : "Bretagne",
    57 : "Grand Est",
    58 : "Bourgogne-France-Comté",
    59 : "Hauts-de-France",
    60 : "Hauts-de-France",
    61 : "Normandie",
    62 : "Hauts-de-France",
    63 : "Auvergne-Rhône-Alpes",
    64 : "Nouvelle-Aquitaine",
    65 : "Occitanie",
    66 : "Occitanie",
    67 : "Grand Est",
    68 : "Grand Est",
    '69D' : "Auvergne-Rhône-Alpes",
    '69M' : "Auvergne-Rhône-Alpes",
    70 : "Bourgogne-France-Comté",
    71 : "Bourgogne-France-Comté",
    72 : "Pays de la loire",
    73 : "Auvergne-Rhône-Alpes",
    74 : "Auvergne-Rhône-Alpes",
    75 : "Île-de-France",
    76 : "Normandie",
    77 : "Île-de-France",
    78 : "Île-de-France",
    79 : "Nouvelle-Aquitaine",
    80 : "Hauts-de-France",
    81 : "Occitanie",
    82 : "Occitanie",
    83 : "Provence-Alpes-Côte d'Azur",
    84 : "Provence-Alpes-Côte d'Azur",
    85 : "Pays de la loire",
    86 : "Nouvelle-Aquitaine",
    87 : "Nouvelle-Aquitaine",
    88 : "Grand Est",
    89 : "Bourgogne-France-Comté",
    90 : "Bourgogne-France-Comté",
    91 : "Île-de-France",
    92 : "Île-de-France",
    93 : "Île-de-France",
    94 : "Île-de-France",
    95 : "Île-de-France",
    971 : "Guadeloupe",
    972 : "Martinique",
    973 : "Guyane",
    974 : "La Réunion",
    976 : "Mayotte",
}

dpt_pref = {
    1 : "Bourg-en-Bresse",
    2 : "Laon",
    3 : "Moulins",
    4 : "Digne-les-Bains",
    5 : "Gap",
    6 : "Nice",
    7 : "Privas",
    8 : "Charleville-Mézières",
    9 : "Foix",
    10 : "Troyes",
    11 : "Carcassonne",
    12 : "Rodez",
    13 : "Marseille",
    14 : "Caen",
    15 : "Aurillac",
    16 : "Angoulême",
    17 : "La Rochelle",
    18 : "Bourges",
    19 : "Tulle",
    '2A' : "Ajaccio",
    '2B' : "Bastia",
    21 : "Dijon",
    22 : "Saint-Brieuc",
    23 : "Guéret",
    24 : "Périgueux",
    25 : "Besançon",
    26 : "Valence",
    27 : "Évreux",
    28 : "Chartres",
    29 : "Quimper",
    30 : "Nîmes",
    31 : "Toulouse",
    32 : "Auch",
    33 : "Bordeaux",
    34 : "Montpellier",
    35 : "Rennes",
    36 : "Châteauroux",
    37 : "Tours",
    38 : "Grenoble",
    39 : "Lons-le-Saunier",
    40 : "Mont-de-Marsan",
    41 : "Blois",
    42 : "Saint-Étienne",
    43 : "Le Puy-en-Velay",
    44 : "Nantes",
    45 : "Orléans",
    46 : "Cahors",
    47 : "Agen",
    48 : "Mende",
    49 : "Angers",
    50 : "Saint-Lô",
    51 : "Châlons-en-Champagne",
    52 : "Chaumont",
    53 : "Laval",
    54 : "Nancy",
    55 : "Bar-le-Duc",
    56 : "Vannes",
    57 : "Metz",
    58 : "Nevers",
    59 : "Lille",
    60 : "Beauvais",
    61 : "Alençon",
    62 : "Arras",
    63 : "Clermont-Ferrand",
    64 : "Pau",
    65 : "Tarbes",
    66 : "Perpignan",
    67 : "Strasbourg",
    68 : "Colmar",
    '69D' : "Lyon",
    '69M' : "Lyon",
    70 : "Vesoul",
    71 : "Mâcon",
    72 : "Le Mans",
    73 : "Chambéry",
    74 : "Annecy",
    75 : "Paris",
    76 : "Rouen",
    77 : "Melun",
    78 : "Versailles",
    79 : "Niort",
    80 : "Amiens",
    81 : "Albi",
    82 : "Montauban",
    83 : "Toulon",
    84 : "Avignon",
    85 : "La Roche-sur-Yon",
    86 : "Poitiers",
    87 : "Limoges",
    88 : "Épinal",
    89 : "Auxerre",
    90 : "Belfort",
    91 : "Évry",
    92 : "Nanterre",
    93 : "Bobigny",
    94 : "Créteil",
    95 : "Cergy",
    971 : "Basse-Terre",
    972 : "Fort-de-France",
    973 : "Cayenne",
    974 : "Saint-Denis",
    976 : "Mamoudzou",
}
