name: deploy

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

# This job installs dependencies, build the stuff, and pushes it to `gh-pages`
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: install latex dependencies
      run: |
        sudo apt-get install texlive-latex-recommended texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-xetex latexmk texlive-lang-french

    # Build the pdf
    - name: Build the pdf
      run: |
        make all

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/

